In [1]:
import pandas as pd
import numpy as np

df = pd.DataFrame(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]),
                   columns=['a', 'b', 'c'])

In [3]:
df

a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [4]:
df.a

0    1
1    4
2    7
Name: a, dtype: int64

# Identify how the colon :  is used as splitter


In [5]:
test1 = np.array([0,1,2,3,4,5,6,7,8,9,10])
# in this case the Index 5 serves as a LIMIT 
# Elements < 5
test1[:5]

array([0, 1, 2, 3, 4])

In [7]:
# in this case the Index 7 serves as an STARTING point
# Elements >= 7
test1[7:]

array([ 7,  8,  9, 10])

In [11]:
#This works the same for Multidimensional Arrays
test2 = np.array([[1,2,3,4,5],[6,7,8,9,10], [11,12,13,14,15]])
#This gets the elements up to index 2
test2[:2] # the response are items = arrays

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [12]:
#Here we split from index 1 
test2[1:]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

# Resulting Matrix sizes of Matrix multiplications

In [29]:
m1 = np.array([  [1,2,3] ])
m2 = np.array([  [1,2,2,2],[2,2,2,2],[3,2,2,2]  ])
m3 = np.dot(m1,m2)
m3.shape

(1, 4)

## if m1 was the input and the m2 was the weights matrix of a multilayer perceptron, the number of rows in the m2 shoud be equals to the number of columns in m1, and the number of columns in the m2 should be equals to the number of neurons in the Net.
## In this example m2 would represent a network layer with 3 inputs and 4 neurons in the layer. With a shape of

In [31]:
m2.shape

(3, 4)

# Trying to find relation between function notations in 2 dimensions and Matrices
$f(x,y) = \begin{bmatrix} x^{3} - 9x\\ y^{3} - 9y  \end{bmatrix}$
<br>
$v1=\begin{bmatrix} 1 & 1 \end{bmatrix}$ , 
$v2=\begin{bmatrix} 1 & 1 \\ 2 & 2 \end{bmatrix}$
<br>


In [20]:
v1 = np.array([1,1])
v2 = np.array([[1,1],[2,2]])

array([[1, 1],
       [2, 2]])

$
v1 · v2 = \begin{bmatrix} 1 & 1 \end{bmatrix} · \begin{bmatrix} 1 & 1 \\ 2 & 2 \end{bmatrix} = \begin{bmatrix} 3 & 3 \end{bmatrix}
$

In [21]:
np.dot(v1,v2)

array([3, 3])

$
v2 · v1 = \begin{bmatrix} 1 & 1 \\ 2 & 2 \end{bmatrix} · \begin{bmatrix} 1 & 1 \end{bmatrix} =  \begin{bmatrix} 2 & 4 \end{bmatrix}
$

In [29]:
np.dot(v2,v1)

array([2, 4])

$v3 = \begin{bmatrix} 1  \\ 1 \end{bmatrix}$
<br>
$
v2 · v3 = \begin{bmatrix} 1 & 1 \\ 2 & 2 \end{bmatrix} · \begin{bmatrix} 1 \\ 1 \end{bmatrix} =  \begin{bmatrix} 2 \\ 4 \end{bmatrix}
$

In [28]:
v3 = np.array([[1],[1]])
np.dot(v2,v3)

array([[2],
       [4]])