In [2]:
import tensorflow as tf
import numpy as np

print("TensorFlow version: ",tf.version.VERSION)

TensorFlow version:  2.6.0


# Lab Task 1: Understand Basic and Advanced Tensor Concepts

## Lets create some basic tensors

In [17]:
# a rank 0 tensor is also a Scaler
rank_0_tensor = tf.constant(4)
print("rank_0_tensor---->",rank_0_tensor)

# a rank 1 tensor is a vector
rank_1_tensor = tf.constant([3,5,7])
print("rank_1_tensor---->", rank_1_tensor)

# a rank 2 tensor is a Matrix
rank_2_tensor = tf.constant([[1,2,3],[4,5,6]])
print("rank_2_tensor---->", rank_2_tensor)

# a rank 3 tensor is a 3D Tensor 
rank_3_tensor = tf.constant([
    [[1,2,3],[4,5,6]],
    [[1,2,3],[4,5,6]]
])
print("rank_3_tensor---->", rank_3_tensor)

# a rank 4 tensor is a nD tensor
rank_4_tensor = tf.stack([rank_3_tensor, rank_3_tensor])
print("rank_4_tensor---->", rank_4_tensor)

"""
We start to see a pattern on the shape attribute. 

Rank   |  Shape
--------------------
0      | ()
1      | (1,)
2      | (n2, n1)
3      | (n3, n2, n1)
4      | (n4,n3,n2, n1)
n      | (n.....n5, n4,n3,n2, n1)
"""

rank_0_tensor----> tf.Tensor(4, shape=(), dtype=int32)
rank_1_tensor----> tf.Tensor([3 5 7], shape=(3,), dtype=int32)
rank_2_tensor----> tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
rank_3_tensor----> tf.Tensor(
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]], shape=(2, 2, 3), dtype=int32)
rank_4_tensor----> tf.Tensor(
[[[[1 2 3]
   [4 5 6]]

  [[1 2 3]
   [4 5 6]]]


 [[[1 2 3]
   [4 5 6]]

  [[1 2 3]
   [4 5 6]]]], shape=(2, 2, 2, 3), dtype=int32)


'\nWe start to see a pattern on the shape attribute. \n\nRank   |  Shape\n--------------------\n0      | ()\n1      | (1,)\n2      | (n2, n1)\n3      | (n3, n2, n1)\n4      | (n4,n3,n2, n1)\nn      | (n.....n5, n4,n3,n2, n1)\n'

I would like to draw the attention to how this image describes the order of the shape indexes:
![Index Order](figs/indexOrder.png)
Remember how the RNN the batch was understood as Stream, the width was the mini-batches, the Height was the mini-batch size and the Features were vectors with only 1 element inside describing the value in the Time Series.


Notice how the features are represented for the most inner vector, this is because the intention is: "This way feature vectors are contiguous regions of memory."
Here is another visualization of the ranks
![Visualization of Ranks](figs/rankShapes.png)

**You can think in the ranks as the number of AXES a tensor has**


Here is another visualization of a rank 4.
Tip: You know rank 3 tensors looks like 3d square shapes, well, when you think about a rank 4, you maybe are expecting to see a pile of 3d objects

![rank 4 tensor visualization](figs/rank4visualization.png)

In [18]:
# These are some other properties you can extract from a tensor that help to describe it
print("Type of every element:", rank_4_tensor.dtype)
print("Number of dimensions:", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along the last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (3*2*4*5): ", tf.size(rank_4_tensor).numpy())

Type of every element: <dtype: 'int32'>
Number of dimensions: 4
Shape of tensor: (2, 2, 2, 3)
Elements along axis 0 of tensor: 2
Elements along the last axis of tensor: 3
Total number of elements (3*2*4*5):  24
