In [2]:
from vector import Vector
from line import Line

In [5]:
v1 = Vector([1,2,3])
v2 = Vector([1,2,3])
print(v1.plus(v2))

Vector: (Decimal('2'), Decimal('4'), Decimal('6'))


# Threshold Logic Unit (TLU) / Linear Threshold Unit(LTU)


<img src="LTU.png">

In [54]:
import numpy as np

X = np.array([  [0.1, 0.1, 0.1] ])
W = np.array([  [0.01],[0.01], [0.01] ])

print('---X---')
print(X)
print('---W---')
print(W)

def step_heaviside(z):
    if z >= 0:
        return 1
    else:
        return 0

print('---Weighted Sum Z---')
z = np.dot(X,W)
print(z)
print('---Output---')
output = step_heaviside(z)
print(output)

---X---
[[0.1 0.1 0.1]]
---W---
[[0.01]
 [0.01]
 [0.01]]
---Weighted Sum Z---
[[0.003]]
---Output---
1


In [18]:


X = np.array([  [17,25,6,2] ])
print(X)
W = np.array([[3],[32], [19], [27]])
print(W)

[[17 25  6  2]]
[[ 3]
 [32]
 [19]
 [27]]


In [24]:
M = np.dot(X,W)
print(M)

[[1019]]


In [35]:
x = np.array([ [1,1,1,1], [2,2,2,2], [3,3,3,3]] )
w =  np.array([[1,2,3,4,5],[1,2,3,4,5], [1,2,3,4,5], [1,2,3,4,5]])
print('---X---')
print(x)
print('---W---')
print(w)
print('Z')
dot = np.dot(x,w)
print(dot)

---X---
[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]]
---W---
[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
Z
[[ 4  8 12 16 20]
 [ 8 16 24 32 40]
 [12 24 36 48 60]]


# The Perceptron
<img src="perceptron.png">

In [46]:
"""
As always, X represents the matrix of input features. 
It has one row per instance and one column per feature.
"""
X = np.array([ [0.1,0.1] ] )
"""
The weight matrix W contains all the connection weights except for the ones from the bias neuron.
It has one row per input neuron and one column per artificial neuron in the layer.
"""
W =  np.array([  [0.1,0.2,0.3],[0.1,0.2,0.3] ])

"""
The bias vector b contains all the connection weights between the bias neuron and the artificial neurons.
It has one bias term per artificial neuron
"""
b = 1


print('---X---')
print(X)
print('---W---')
print(W)

---X---
[[0.1 0.1]]
---W---
[[0.1 0.2 0.3]
 [0.1 0.2 0.3]]


In [47]:
XW= np.dot(X,W)
input_to_Activation_function = XW + b
print(f'ø({input_to_Activation_function})')

ø([[1.02 1.04 1.06]])


## When The Artificial Neurons are TLU, the  activation function  is a step function (but this can accomodate other types of activation)