In [13]:
import numpy as np

A = np.array([
            [-2,4,-2,-1,4],
            [4,-8,3,-3,1],
            [1,-2,1,-1,1],
            [1,-2,0,-3,4],
             ])
b = np.array([-3,2,0])

def swap_row(matrix,idx1, idx2):
    temp = np.array(matrix[idx1])    
    matrix[idx1] = matrix[idx2]
    matrix[idx2] = temp
    return matrix

print(A)
A = swap_row(A,0,2)
print(A)
A[1] = A[1] -(4*A[0])
A[2] = A[2] +(2*A[0])
A[3] = A[3] -(A[0])
print(A)
A[3] = A[3] - (A[1])-(A[2])
print(A)
A[1] = A[1] * (-1)
A[2] = A[2] * (-1/3)
print(A)

[[-2  4 -2 -1  4]
 [ 4 -8  3 -3  1]
 [ 1 -2  1 -1  1]
 [ 1 -2  0 -3  4]]
[[ 1 -2  1 -1  1]
 [ 4 -8  3 -3  1]
 [-2  4 -2 -1  4]
 [ 1 -2  0 -3  4]]
[[ 1 -2  1 -1  1]
 [ 0  0 -1  1 -3]
 [ 0  0  0 -3  6]
 [ 0  0 -1 -2  3]]
[[ 1 -2  1 -1  1]
 [ 0  0 -1  1 -3]
 [ 0  0  0 -3  6]
 [ 0  0  0  0  0]]
[[ 1 -2  1 -1  1]
 [ 0  0  1 -1  3]
 [ 0  0  0  1 -2]
 [ 0  0  0  0  0]]
